# API Configuration
API_URL = "http://localhost:8000/api/v1"  # Change to deployed API URL

# Database (if needed)
DATABASE_URL = "sqlite:///./finance.db"

# Security
SECRET_KEY = "your-secret-key-here"
ALGORITHM = "HS256"

# OCR Path (for Streamlit Cloud)
TESSERACT_CMD = "/usr/bin/tesseract"
