# API Configuration
API_URL = "https://ai-finance-api-sj9l.onrender.com/api/v1"


# Database (if needed)
DATABASE_URL = "sqlite:///./finance.db"

# Security
SECRET_KEY = "your-secret-key-here"
ALGORITHM = "HS256"

# OCR Path (for Streamlit Cloud)
TESSERACT_CMD = "/usr/bin/tesseract"
